name: API WebApp CI/CD

on:
  push:
    branches: [ "main" ]
    paths:
      - "scr/WebApi/**"
      - ".github/workflows/api-webapp.yml"
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    env:
      APPLICATION_NAME: "app-wowow-wpi-dev-001"
      DOTNET_VERSION: "10.x" 
      PROJECT_PATH: "src/WebApi/WebApi.csproj" #src/WebApi/WebApi.csproj

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore
        run: dotnet restore $PROJECT_PATH

      - name: Build
        run: dotnet build ${{ env.DOTNET_VERSION }} --configuration Release --no-restore

      - name: Publish
        run: dotnet publish ${{ env.DOTNET_VERSION }} --configuration Release  --output ./publish

      - name: Configure app seetings and ports
        run: az webapp config appsettings set \
             -g ${{ secrets.AZURE_RESOURCE_GROUP }} \
             -n ${{ secrets.AZURE_WEBAPP_API_NAME }} \
             --settings ASPNETCORE_URLS=http://*:80 PORT=80

      - name: Deploy to Azure Web App (API)
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.APPLICATION_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_API }}
          package: ./publish
