name: API WebApp CI/CD

on:
  push:
    branches: [ "main" ]
    paths:
      - "WebApi/**"
      - ".github/workflows/api-webapp.yml"
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      APPLICATION_NAME: "app-wowow-wpi-dev-001"
      DOTNET_VERSION: "10.0.x" 
      PROJECT_PATH: "src/WebApi/WebApi.csproj" 
      

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore
        run: dotnet restore $PROJECT_PATH

      - name: Build
        run: dotnet build $PROJECT_PATH --configuration Release --no-restore

      - name: Publish
        run: dotnet publish $PROJECT_PATH --configuration Release --output ./publish

      - name: Deploy to Azure Web App (API)
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.APPLICATION_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_API }}
          package: ./publish
